VSPHERE_SERVER: '192.168.255.161'
VSPHERE_USERNAME: 'Administrator@vsphere.labrca.local'
VSPHERE_PASSWORD:  'Azerty@01'
VSPHERE_DATACENTER: '/Datacenter'
VSPHERE_DATASTORE: 'datastore3'
VSPHERE_NETWORK: 'tkg-network'
VSPHERE_RESOURCE_POOL: '/Datacenter/host/192.168.255.160/Resources/TKG'
VSPHERE_FOLDER: '/Datacenter/vm/TKG'
VSPHERE_SSH_AUTHORIZED_KEY: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC6ElaXKL+elJQ9sa1GlIswxwLm1RH4bme3uOvztyYgbdJ8AvLeoCjP0LPe+38mM1N+93NebGXDW1cYs7J8Csqt6TgPaLj1T99FIuZF7Aql6EaDQ1QOTNB08EtPuk4BFSHfphP0lwYUyrIZE4L+Mg8bjnJOzt21hFJRepFg8xMzPo+5UxxqgDMQLF+225VpYBcoaHrudwLRC/1ObkXlrlsjZBoTFeZMYZfUYePzrMiCh9T/mQmqbc7yNg3Rd3YSBkz2v7B4aVPWYY+cZvxLfPJoAkAI+eHNXo4Td3+ntPdUscPl8ZdyoWVuo60K1IMCK2spb6FROgif+PBKBp8bj6rV regis.camy@kardol@KLI-RCA"
VSPHERE_TEMPLATE: photon-3-kube-v1.19.3_vmware.2