---
- name: Joining an existing AD domain
  hosts: all
  vars:
    domainname: EXAMPLE.COM
    dnsname: example.com
    domain_admin: Administrator@example.com

  tasks:
    - name: Joining the domain "{{ domainname }}"
      win_domain_membership:
        dns_domain_name: "{{ dnsname }}"
        domain_admin_user: "{{ domain_admin }}"
        domain_admin_password: "{{ password }}"
        state: domain
      register: domain_state

    - name: Rebooting to join the domain
      win_reboot:
        msg: "Rebooting..."
      when: domain_state.reboot_required


- name: Manage page files
  hosts: Windows

  tasks:
    - name: Obtain page file information
      win_pagefile:
      register: orig_pagefile_info

    - name: Show original page file information
      debug:
        var: orig_pagefile_info

    - name: Manage page files on virtual machines
      win_pagefile:
        remove_all: "{{ pagefile['remove'] }}"
        automatic: "{{ pagefile['auto'] }}"
      register: new_pagefile_info

    - name: Show new page file information
      debug:
        var: new_pagefile_info

    - name: Show current memory information
      debug:
        var: ansible_facts['memtotal_mb']

- name: System summary is compiled
  hosts: all
  tasks:
    - name: Product facts are collected
      win_product_facts:

    - name: Disk facts are collected
      win_disk_facts:

    - name: Summary is written
      win_copy:
        content: |
          OS: {{ ansible_facts['os_name'] }}
          Machine ID: {{ ansible_facts['machine_id'] }}
          Last Boot: {{ ansible_facts['lastboot'] }}
          License Status: {{ ansible_facts['os_license_status'] }}
          Disk Size: {{ ansible_facts['disks'][0]['size'] }}
        dest: "{{ ansible_facts['user_dir'] }}\\Desktop\\summary-{{ ansible_facts['hostname'] }}.txt"
